### ISSUE TITLE
NullPointerError on FAT32

### ISSUE THREAD

**Issue by n-nishizawa** [djberg96/win32-file-security#2]
Could you please tell me whether this gem supports FAT32 filesystem or not?

I tried to get permissions on FAT32. 
But I got an error below. 
The drive `E:` is a USB flash drive and is formatted as FAT32. 

```
[4] pry(main)>
[5] pry(main)> require 'win32/file/security'
=> true
[6] pry(main)>
[7] pry(main)>
[8] pry(main)> File.get_permissions('C:\\')
=> {"BUILTIN\\Administrators"=>268435456,
 "NT AUTHORITY\\SYSTEM"=>268435456,
 "BUILTIN\\Users"=>1179817,
 "NT AUTHORITY\\Authenticated Users"=>4}
[9] pry(main)>
[10] pry(main)>
[11] pry(main)>
[12] pry(main)>
[13] pry(main)> File.get_permissions('E:\\')
FFI::NullPointerError: invalid memory read at address=0x000000
from <RUBY_INSTALL_DIR>/lib/ruby/gems/2.1.0/gems/win32-file-security-1.0.4/lib/win32/file/security.rb:228:in `[]'
[14] pry(main)>
```

**Comment by djberg96** [comment]
No, it doesn't support FAT/FAT32 because you cannot get or set security information on that filesystem as far as I know. Somewhat surprisingly the GetFileSecurity function doesn't fail on FAT32, but instead it's basically a no-op. So, the code goes on its merry way until it tries to access DACL information that doesn't exist.

I'll see if I can find a way to catch that so you get a nicer error message at least.

**Comment by djberg96** [comment]
Can you checkout the fat32_handler branch and see if that worked? It will still fail, but it will catch the error sooner and (hopefully) make it more clear that FAT32 isn't supported.

**Comment by djberg96** [comment]
Nevermind, found a thumb drive already FAT formatted, and my initial attempt to fix it did not work.

**Comment by djberg96** [comment]
Ok, I've added an explicit check for ACL support in 1.0.5. I've also added a singleton method File.supports_acls? to the class.

Thanks for the report!

**Comment by n-nishizawa** [comment]
Thank you so much for your quick response !!
 I didn't know that FAT32 doesn't support ACL.

I really appreciate it.

**Comment by djberg96** [comment]
Yeah, it was added with NTFS. There's really no reason to use FAT32 any more at all that I'm aware of.
