### ISSUE TITLE
Cannot round-trip permissions on Windows 10

### ISSUE THREAD

**Issue by aogail** [djberg96/win32-file-security#4]
Using win32-file-security 1.0.7 on Windows 10, the following code fails because of an `Everyone` entry in the file permissions.

``` ruby
require 'win32/file/security'
perms = File.get_permissions('file.txt')
puts perms.inspect
File.set_permissions('file.txt', perms)
```

On my Windows 10 system, running in a shell as Administrator, I receive the following exception:

```
{"NT AUTHORITY\\SYSTEM"=>2032127, "BUILTIN\\Administrators"=>2032127, "CAP-DEV-ENVIRON\\IEUser"=>2032127, "BUILTIN\\Users"=>1179817, "Everyone"=>1179817}
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/win32-file-security-1.0.7/lib/win32/file/security.rb:414:in `block in set_permissions': undefined method `wincode' for nil:NilClass (NoMethodError)
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/win32-file-security-1.0.7/lib/win32/file/security.rb:403:in `each'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/win32-file-security-1.0.7/lib/win32/file/security.rb:403:in `set_permissions'
        from perms.rb:4:in `<main>'
```

This appears to be caused because in `win32/file/security.rb`, at line 406, it splits the account string on `\`. However, `Everyone` does not have a backlash in it, so `wide_account` becomes nil.

I'm not certain, but perhaps if there is no server part in `account`, `wide_server` should be set to nil and `account` be the full original value -- `Everyone` in my example.

**Comment by aogail** [comment]
@djberg96 Does that solution sound OK to you? If so I'll submit a PR. I cloned the repository and noticed that this failure is already exposed by one of the unit tests on my Windows 10 box. Adding logic to deal with `account.nil?` fixed the failing test.

**Comment by djberg96** [comment]
@aogail Sounds right to me. Please submit a PR.
