### ISSUE TITLE
account_rights not correctly reset in set_permissions

### ISSUE THREAD

**Issue by tomcbe** [djberg96/win32-file-security#7]
Hi @djberg96 

I think we discovered a bug in the function set_permissions in lib/win32/file/security.rb:

When set_permissions is called with a hash with permissions for multiple accounts, the variable account_rights is not reset to 0 when the next account is handled. We simply moved the line `account_rights = 0` into the loop `perms.each{ |account, mask|` to fix this.

I sent you a pull request ( #6 ), if you would like to include our fix in the next version.

Regards
tomcbe

**Comment by djberg96** [comment]
Looks right to me. @phasis68 Do you concur?

**Comment by phasis68** [comment]
I concur.

**Comment by djberg96** [comment]
Thanks. Merged.
