### ISSUE TITLE
Missing dependency for ffi-win32-extensions

### ISSUE THREAD

**Issue by tomcbe** [djberg96/win32-file-security#8]
Hi @djberg96 

I think you forgot to add the runtime dependency for ffi-win32-extensions in the gemspec after removing the helper in https://github.com/djberg96/win32-file-security/commit/a16311429cb5160e4d97d57ee21855417280bf94

Im getting the following error when using get_permissions:
`NoMethodError: undefined method `wstrip' for "B\x00e\x00n\x00u\x00t\x00z\x00e\x00r\x00":String
C:/docuteam/apps/Ruby22-x64/lib/ruby/gems/2.2.0/gems/win32-file-security-1.0.9/l
ib/win32/file/security.rb:315:in `block in get_permissions'`

When I add the dependency manually in the Gemfile, it works.

Cheers
Thomas

**Comment by djberg96** [comment]
Well, shit. I'll get an update out asap. Thanks for the report.

**Comment by djberg96** [comment]
Fixed in 1.0.10!
